name: Big World Creative Arts
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6146880877204239
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0000a0'
    - '#d50000'
    - '#9ab020'
    - '#d562fe'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
